version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: b1019xxx
      POSTGRES_PASSWORD: "pass"
      POSTGRES_DB: "pg"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    container_name: postgres-db
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d